-- Session 8: Trading and P&L tables
-- Execute & P&L (paper first, real optional)

-- Orders placed (paper or live)
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id UUID NULL,
  market_id TEXT NOT NULL,
  token_id TEXT NULL,               -- YES token
  side TEXT NOT NULL CHECK (side IN ('YES','NO')),
  qty NUMERIC NOT NULL,             -- in shares
  limit_price NUMERIC NULL,         -- optional
  tif TEXT NOT NULL DEFAULT 'IOC',  -- IOC | DAY (paper uses IOC)
  mode TEXT NOT NULL DEFAULT 'paper',
  comment TEXT NULL,
  config_snapshot JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fills generated by executor (paper or live)
CREATE TABLE IF NOT EXISTS fills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  market_id TEXT NOT NULL,
  token_id TEXT NULL,
  side TEXT NOT NULL,
  qty NUMERIC NOT NULL,             -- filled shares
  price NUMERIC NOT NULL,           -- avg fill price
  fee_bps INTEGER NOT NULL,
  fee_usdc NUMERIC NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Positions snapshot (optional materialized, or compute on the fly)
CREATE TABLE IF NOT EXISTS positions (
  market_id TEXT PRIMARY KEY,
  token_id TEXT NULL,
  side TEXT NOT NULL,               -- 'YES' net >0 else 'NO' (if you support short later)
  qty NUMERIC NOT NULL,             -- net shares (>0 long)
  vwap NUMERIC NOT NULL,            -- average entry price
  realized_pnl NUMERIC NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- P&L equity curve (snapshots)
CREATE TABLE IF NOT EXISTS equity_curve (
  ts TIMESTAMPTZ PRIMARY KEY,
  equity_usdc NUMERIC NOT NULL,
  realized_usdc NUMERIC NOT NULL,
  unrealized_usdc NUMERIC NOT NULL,
  fees_usdc NUMERIC NOT NULL
);

-- Risk config/runtime state
CREATE TABLE IF NOT EXISTS risk_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  trading_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  daily_pnl_start_usdc NUMERIC NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_orders_market_id ON orders(market_id);
CREATE INDEX IF NOT EXISTS idx_orders_ts ON orders(ts);
CREATE INDEX IF NOT EXISTS idx_fills_market_id ON fills(market_id);
CREATE INDEX IF NOT EXISTS idx_fills_ts ON fills(ts);
CREATE INDEX IF NOT EXISTS idx_fills_order_id ON fills(order_id);
CREATE INDEX IF NOT EXISTS idx_equity_curve_ts ON equity_curve(ts);

-- Initialize risk state
INSERT INTO risk_state (id, trading_enabled) 
VALUES (1, TRUE) 
ON CONFLICT (id) DO NOTHING;